name: zcashd-nightly

on:
  schedule:
    - cron: '0 6 * * *' # Every day at 6:00 AM UTC.

jobs:
  install-zcashd:
    runs-on: ubuntu-latest
    steps:
      - name: clone zcashd
        run: git clone https://github.com/zcash/zcash
      - name: build zcashd
        run: |
          cd zcash
          ./zcutil/build.sh -j$(nproc)
      - uses: actions/upload-artifact@v3
        with:
          name: zcashd-fetch-params
          path: ./zcash/zcutil/fetch-params.sh
      - uses: actions/upload-artifact@v3
        with:
          name: zcashd-executable
          path: ./zcash/src/zcashd

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Compile unit tests
        run: cargo test --all-targets --no-run
      - uses: actions/upload-artifact@v3
        with:
          name: ziggurat-executable
          path: ./target/debug/deps/ziggurat-*

  test-zcashd:
    runs-on: ubuntu-latest
    needs: [ check, install-zcashd ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: rustup toolchain install nightly --profile minimal
      - uses: actions/download-artifact@v3
        with:
          name: zcashd-fetch-params
          path: ./zcash
      - uses: actions/download-artifact@v3
        with:
          name: zcashd-executable
          path: ./zcash
      - uses: actions/download-artifact@v3
        with:
          name: ziggurat-executable
          path: ./ziggurat
      - name: Create ~/.ziggurat/config.toml
        run: |
          mkdir ~/.ziggurat/
          touch ~/.ziggurat/config.toml
          echo kind = \"zcashd\" > ~/.ziggurat/config.toml
          echo path = \"/home/runner/work/zcash/zcash/zcash\" >> ~/.ziggurat/config.toml
          echo start_command = \"./zcashd -debug=1 -printtoconsole -logips=1 -dnsseed=0 -dns=0 -listenonion=0\" >> ~/.ziggurat/config.toml
      - name: Fetch zcashd params
        run: |
          chmod +x zcash/fetch-params.sh
          ./zcash/fetch-params.sh
      - name: Run ziggurat suite
        continue-on-error: true
        run: |
          rm ./ziggurat/*.d
          mv ./ziggurat/ziggurat-* ziggurat_test
          chmod +x ziggurat_test
          chmod +x zcash/zcashd
          mkdir -p results/zcashd
          ./ziggurat_test --test-threads=1 --nocapture -Z unstable-options --report-time --format json > result.jsonl
      - name: git
        run: |
          FILENAME=$(date +%Y-%m-%d)
          mv result.jsonl results/zcashd/$FILENAME.jsonl
          rm -f results/zcashd/latest.jsonl
          cp results/zcashd/$FILENAME.jsonl results/zcashd/latest.jsonl
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git add results
          git commit -m "ci: zcashd suite results"
          git push
