name: zebra

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # Every day at 6:00 AM UTC.

jobs:
  build-zebra:
    runs-on: ubuntu-latest
    outputs:
      commit-hash: ${{ steps.commit-hash.outputs.commit-hash }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ZcashFoundation/zebra
      - name: Build Zebra and download artifacts
        run: cargo build --release
      - name: Grab short commit hash and store in env
        id: commit-hash
        run: echo commit-hash=$(git log -n 1 --pretty=format:"%h") >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v3
        with:
          name: node-executable
          path: ./target/release/zebrad

  build-ziggurat:
    uses: zeapoz/ziggurat-core/.github/workflows/build-ziggurat.yml@ci/pin-cargo

  run-test-suite:
    runs-on: ubuntu-latest
    needs: [ build-zebra, build-ziggurat ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: node-executable
          path: ./
      - run: chmod +x zebrad
      - name: Create Ziggurat config file
        run: |
          mkdir ~/.ziggurat/
          echo 'kind = "zebra"' > ~/.ziggurat/config.toml
          echo 'path = "/home/runner/work/zcash/zcash"' >> ~/.ziggurat/config.toml
          echo 'start_command = "./zebrad start"' >> ~/.ziggurat/config.toml
      - name: Run Ziggurat test suite
        uses: runziggurat/ziggurat-core@main
        with:
          node-name: zebrad
          commit-hash: ${{ needs.build-zebra.outputs.commit-hash }}

  process-results:
    needs: [ run-test-suite ]
    uses: runziggurat/ziggurat-core/.github/workflows/process-results.yml@main
    with:
      name: zebra
      repository: zcash
    secrets:
      gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
